apiVersion: v1
kind: Template
labels:
  template: openjdk-jenkins-pipeline
  xpaas: 1.4.17
message: A new java application has been created in your project.
metadata:
  annotations:
    description: An example Java application using OpenJDK, and Jenkinsfile build pipeline
    openshift.io/display-name: OpenJDK Jenkins Pipeline
    tags: java
  name: openjdk-jenkins-pipeline
objects:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
      buildconfig: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    failedBuildsHistoryLimit: 5
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}:latest
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: redhat-openjdk18-openshift:${REDHAT_OPENJDK_VERSION}
          namespace: openshift
      type: Source
    successfulBuildsHistoryLimit: 5
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
    replicas: ${DEFAULT_REPLICAS}
    template:
      metadata:
        labels:
          app: ${APPLICATION_NAME}
          deploymentconfig: ${APPLICATION_NAME}
      spec:
        containers:
        - image: ${APPLICATION_NAME}
          imagePullPolicy: Always
          name: ${APPLICATION_NAME}
          ports:
          - containerPort: 8080
            protocol: TCP
parameters:
- description: The name for the application.
  displayName: Application Name
  name: APPLICATION_NAME
  required: true
  value: spring-example-ocp
- description: The version of the redhat-openjdk18-openshift image stream to use
  displayName: redhat-openjdk18-openshift version
  name: REDHAT_OPENJDK_VERSION
  value: '1.4'
- description: This specifies how many replicas are created by default
  displayName: Replicas
  name: DEFAULT_REPLICAS
  value: '1'