apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    openshift.io/deployer-pod.completed-at: 2019-02-07 14:14:53 +0000 UTC
    openshift.io/deployer-pod.created-at: 2019-02-07 14:14:49 +0000 UTC
    openshift.io/deployer-pod.name: hello-world-apps-1-deploy
    openshift.io/deployment-config.latest-version: "1"
    openshift.io/deployment-config.name: hello-world-apps
    openshift.io/deployment.phase: Complete
    openshift.io/deployment.replicas: "1"
    openshift.io/deployment.status-reason: config change
    openshift.io/encoded-deployment-config: |
      {"kind":"DeploymentConfig","apiVersion":"apps.openshift.io/v1","metadata":{"name":"hello-world-apps","namespace":"myproject","selfLink":"/apis/apps.openshift.io/v1/namespaces/myproject/deploymentconfigs/hello-world-apps","uid":"6d5bb5bd-2ae2-11e9-807e-5254002b4feb","resourceVersion":"4345","generation":2,"creationTimestamp":"2019-02-07T14:12:39Z","labels":{"app":"hello-world-apps"},"annotations":{"openshift.io/generated-by":"OpenShiftNewApp"}},"spec":{"strategy":{"type":"Rolling","rollingParams":{"updatePeriodSeconds":1,"intervalSeconds":1,"timeoutSeconds":600,"maxUnavailable":"25%","maxSurge":"25%"},"resources":{},"activeDeadlineSeconds":21600},"triggers":[{"type":"ConfigChange"},{"type":"ImageChange","imageChangeParams":{"automatic":true,"containerNames":["hello-world-apps"],"from":{"kind":"ImageStreamTag","namespace":"myproject","name":"hello-world-apps:latest"},"lastTriggeredImage":"172.30.1.1:5000/myproject/hello-world-apps@sha256:d69d93a74f0ccee6cd43089ab3c36da3074d02b586b3bdc4559dbea4fe16a97e"}}],"replicas":1,"revisionHistoryLimit":10,"test":false,"selector":{"app":"hello-world-apps","deploymentconfig":"hello-world-apps"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"hello-world-apps","deploymentconfig":"hello-world-apps"},"annotations":{"openshift.io/generated-by":"OpenShiftNewApp"}},"spec":{"containers":[{"name":"hello-world-apps","image":"172.30.1.1:5000/myproject/hello-world-apps@sha256:d69d93a74f0ccee6cd43089ab3c36da3074d02b586b3bdc4559dbea4fe16a97e","ports":[{"containerPort":8778,"protocol":"TCP"},{"containerPort":8080,"protocol":"TCP"},{"containerPort":8443,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"Always"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}}},"status":{"latestVersion":1,"observedGeneration":1,"replicas":0,"updatedReplicas":0,"availableReplicas":0,"unavailableReplicas":0,"details":{"message":"config change","causes":[{"type":"ConfigChange"}]},"conditions":[{"type":"Available","status":"False","lastUpdateTime":"2019-02-07T14:12:39Z","lastTransitionTime":"2019-02-07T14:12:39Z","message":"Deployment config does not have minimum availability."}]}}
  creationTimestamp: 2019-02-07T14:14:49Z
  generation: 2
  labels:
    app: hello-world-apps
    openshift.io/deployment-config.name: hello-world-apps
  name: hello-world-apps-1
  namespace: myproject
  ownerReferences:
  - apiVersion: apps.openshift.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: DeploymentConfig
    name: hello-world-apps
    uid: 6d5bb5bd-2ae2-11e9-807e-5254002b4feb
  resourceVersion: "4404"
  selfLink: /api/v1/namespaces/myproject/replicationcontrollers/hello-world-apps-1
  uid: badebcb4-2ae2-11e9-98b0-5254002b4feb
spec:
  replicas: 1
  selector:
    app: hello-world-apps
    deployment: hello-world-apps-1
    deploymentconfig: hello-world-apps
  template:
    metadata:
      annotations:
        openshift.io/deployment-config.latest-version: "1"
        openshift.io/deployment-config.name: hello-world-apps
        openshift.io/deployment.name: hello-world-apps-1
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: hello-world-apps
        deployment: hello-world-apps-1
        deploymentconfig: hello-world-apps
    spec:
      containers:
      - image: 172.30.1.1:5000/myproject/hello-world-apps@sha256:d69d93a74f0ccee6cd43089ab3c36da3074d02b586b3bdc4559dbea4fe16a97e
        imagePullPolicy: Always
        name: hello-world-apps
        ports:
        - containerPort: 8778
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  fullyLabeledReplicas: 1
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
