
node('maven') {
    def projectPrefix = "sample-pipeline"

    // Checkout Source Code.
    stage('Checkout Source') {
        checkout scm
    }

    stage('Build in dev') {
        // switch to dev project
        sh "oc project ${projectPrefix}-dev"

        // run build
        sh "mvn fabric8:build"
    }

    stage('Deploy to dev') {
        // trigger deploy
        sh "oc rollout latest dc/sample-pipeline"
    }
}